"""
Generate Empirical Benchmark Summary Tables for Paper and Documentation.

Executes baseline strategy comparisons across missingness regimes and outputs:
- paper/tables/benchmark_table.md
- paper/tables/benchmark_raw.csv
"""

import argparse
from pathlib import Path

import pandas as pd

from benchmarks.router_benchmark import compare_router_against_baselines


def generate_paper_tables(
    quick: bool = False, output_dir: Path = Path("paper/tables")
) -> pd.DataFrame:
    output_dir.mkdir(parents=True, exist_ok=True)

    if quick:
        n_replications = 2
        n_samples = 300
        print(f"Generating paper tables in QUICK mode (R={n_replications}, N={n_samples})...")
    else:
        n_replications = 20
        n_samples = 2500
        print(f"Generating paper tables in FULL mode (R={n_replications}, N={n_samples})...")

    df_summary = compare_router_against_baselines(
        n_replications=n_replications,
        n_samples=n_samples,
        missing_rate=0.30,
        base_seed=42,
    )

    # Save raw CSV
    raw_csv_path = output_dir / "benchmark_raw.csv"
    df_summary.to_csv(raw_csv_path, index=False)
    print(f"Saved raw results to: {raw_csv_path}")

    # Format Markdown Table
    md_lines = [
        f"<!-- Generated by scripts/generate_paper_tables.py (R={n_replications}, N={n_samples}) -->",
        "",
        "| Missingness Regime | Strategy / Estimator | Mean Bias | Cell RMSE | 95% Coverage | Downstream Beta Error |",
        "| :--- | :--- | :---: | :---: | :---: | :---: |",
    ]

    for _, row in df_summary.iterrows():
        reg = row["Regime"]
        strat = row["Strategy"]
        bias = f"{row['Mean Bias']:+.3f}"
        rmse = f"{row['Cell RMSE']:.3f}"
        cov = f"{row['Coverage 95']:.1%}"
        beta_err = f"{row['Beta Total Error']:.3f}"
        md_lines.append(f"| **{reg}** | {strat} | {bias} | {rmse} | {cov} | {beta_err} |")

    table_md_path = output_dir / "benchmark_table.md"
    table_md_path.write_text("\n".join(md_lines) + "\n", encoding="utf-8")
    print(f"Saved Markdown table to: {table_md_path}")
    return df_summary


def main():
    parser = argparse.ArgumentParser(description="Generate benchmark tables for paper.")
    parser.add_argument("--quick", action="store_true", help="Run fast smoke benchmark")
    parser.add_argument("--output-dir", type=str, default="paper/tables", help="Output directory")
    args = parser.parse_args()

    generate_paper_tables(quick=args.quick, output_dir=Path(args.output_dir))


if __name__ == "__main__":
    main()
